function [fitresult, gof] = createFit(theta, diff)
%CREATEFIT(THETA,DIFF)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : theta
%      Y Output: diff
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 10-Mar-2022 21:56:36


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( theta, diff );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.SmoothingParam = 0.0126826579464565;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData);
legend( h, 'diff vs. theta', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel('\theta_{in}(^o)','interpreter' , 'tex') ; 
ylabel('\Delta V (V)'   , 'interpreter', 'tex') ; 
grid on


