function [fitresult, gof] = fit1(bx, v2x)
%CREATEFIT(BX,V2X)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : bx
%      Y Output: v2x
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 29-Apr-2022 19:42:07


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( bx, v2x );

% Set up fittype and options.
ft = fittype( 'poly2' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'v2x vs. bx', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'bx', 'Interpreter', 'none' );
ylabel( 'v2x', 'Interpreter', 'none' );
grid on


