function i_v_theory(X1, Y1, X2, Y2, X3, Y3, XData1, YData1)
%CREATEFIGURE(X1, Y1, X2, Y2, X3, Y3, XData1, YData1)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data
%  XDATA1:  line xdata
%  YDATA1:  line ydata

%  Auto-generated by MATLAB on 21-Nov-2021 19:09:36

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'LineWidth',1.5,'Color',[0 0 0]);

% Create plot
plot(X2,Y2,'LineWidth',1.5,'Color',[0 0 1]);

% Create plot
plot(X3,Y3,'LineWidth',1.5,'Color',[1 0 0]);

% Create line
line(XData1,YData1,'Parent',axes1,'LineStyle','--');

% Create light
light('Parent',axes1,'Position',[-0.882734829504749 0.356753034006338 0.305788314862575]);

% Create ylabel
ylabel('I_A(V_A)','FontSize',12);

% Create xlabel
xlabel('V_A','FontSize',12);

% Create title
title({'T=constant'});

box(axes1,'on');
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'YTick',[0 0.5 1 1.5 2 2.5 3 3.5 4 4.5 5 5.5 6]);
% Create textbox
annotation(figure1,'textbox',...
    [0.162785714285714 0.492857142857143 0.0732857142857143 0.0685714285714292],'String',{'???.?'},...
    'FontName','Cambria Math',...
    'FitBoxToText','off');

% Create textbox
annotation(figure1,'textbox',...
    [0.302071428571428 0.520476190476192 0.0732857142857142 0.0685714285714292],'String','???.??',...
    'FontName','Cambria Math',...
    'FitBoxToText','off');

% Create textbox
annotation(figure1,'textbox',...
    [0.604928571428571 0.621428571428574 0.0868571428571433 0.0685714285714295],'String','???.???',...
    'FontName','Cambria Math',...
    'FitBoxToText','off');

% Create arrow
annotation(figure1,'arrow',[0.130357142857143 0.881785714285714],[0.109 0.111904761904762]);

% Create arrow
annotation(figure1,'arrow',[0.283214285714286 0.283214285714286],...
    [0.106190476190476 0.890952380952381]);

% Create textbox
annotation(figure1,'textbox',...
    [0.771357142857143 0.0309523796808153 0.0685714297805514 0.077142858414423],'String',{'V_A'},...
    'FitBoxToText','off',...
    'EdgeColor',[1 1 1]);

% Create textbox
annotation(figure1,'textbox',...
    [0.18635714285714 0.807142855871298 0.0685714297805511 0.077142858414423],'String','I_A(V_A)',...
    'FitBoxToText','off',...
    'EdgeColor',[1 1 1]);

